### PR TITLE
Support mozilla hosted pastebin service

### PR DESCRIPTION
**Pull request by condy0919**
* Extend the default langauge list

### CODE REVIEW

**Comment by condy0919** [comment]
fix #44

**Comment by etu** [comment]
Hey! Thank's for this contribution. Do you mind adding an integration test for this provider as well?

They are located in this file: https://github.com/etu/webpaste.el/blob/master/tests/integration/test-webpaste-providers.el

The `[ci]` or `[local]` at the end of the name of the test determines if it's executed on travis or not. Certain providers doesn't like traffic from travis.

But add it as `[ci]` first and we'll see if it works on travis :slightly_smiling_face:

**Comment by condy0919** [comment]
After adding integration test, the coverage decreased, weird

**Comment by etu** [comment]
So we had a failure of the integration test here: https://travis-ci.org/etu/webpaste.el/jobs/655650677#L532

But I don't see why that would fail, may be because of running on travis.

I'm gonna test a bit locally and see. I don't think you have actually broken the test.

**Comment by condy0919** [comment]
Thanks

**Comment by etu** [comment]
I still don't know why it breaks. It seems to be depending on what data is sent to the provider as the test because locally I get a 401 in response. But if I pull the provider in to my running Emacs and use it on some lisp I get a working link. So your provider definition is fine.

I've tried to add to the message to make it bigger and to set another major-mode to set another lexer in the request. But still 401.

But I'd rather have the provider in than having working tests for every single but. So drop the test so we can get this provider merged :-)

**Comment by etu** [comment]
I've just merged all commits from here except the tests in 2d0f810aefb8c1348e88d836508b53ac0993bf55. Thanks for your contribution :slightly_smiling_face: 

This fixes #44.

**Comment by condy0919** [comment]
https://github.com/etu/webpaste.el/pull/45/files#diff-df1f4cda5a9538ecc6368ffed24557a2R116

The leading `'` cause the error

**Comment by etu** [comment]
Oooh, thanks!

I've updated master with this now:
https://github.com/etu/webpaste.el/commit/ef33b0f298bf36cfb84b37af4870706fc376b0c3

I hope it builds on travis otherwise I'll have to tag it as local :)

**Comment by etu** [comment]
Yep, it works on travis as well: https://travis-ci.org/etu/webpaste.el/jobs/655717165#L523

**Pull request closed without merging**
