### PR TITLE
Detect lang from shebang

### PR DESCRIPTION
**Pull request by kaushalmodi**
Update the lang alist for ptpb.pw for bash, sh, csh, tcsh, python3 and
nim.

Fixes https://github.com/etu/webpaste.el/issues/28.

### CODE REVIEW

**Comment by kaushalmodi** [comment]
I've rebased.

**Comment by etu** [comment]
@kaushalmodi I'm thinking if there's an easy way to write a unit-test for this function, it would be great to have but I can look into that :-)

**Comment by kaushalmodi** [comment]
@etu I am pro-test writing.. but I stumbled at the buttercup package. I have never used it.

Unit test example:

```
# foo.py
#!/usr/bin/env bash
# -*- python -*-
# Above forces incorrect major mode
echo "Hello"
```

This should make `webpaste--get-shebang-lang-mode` return `bash-mode` (symbol). If you can force ptpb.py backend for that test, `webpaste--get-buffer-language` should return `"bash"` and not `"python"`.

**Comment by etu** [comment]
@kaushalmodi I've pushed to a branch here to show you my progress so far. I've created a test for the function here: https://github.com/etu/webpaste.el/commit/56d817dca76c120c0a531fcaaa2270b5dffeff62

I'm working on the tests for `webpaste--get-buffer-language` as well :smiley:

**Pull request merged**
